### ISSUE TITLE
Login form-Admin-app - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#3]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221019221-e0ef4eef-4185-444c-99e2-b5d615a16fe9.png)

**Comment by sookwalinga** [comment]
> > @peculiaruc I am not seeing any issue for the signup page though
> 
> This is Admins app, he/she is not supposed to Sign up.

Oh ok, so meaning the part: "New User? Signup" shouldn't be on this page, right?

**Comment by sookwalinga** [comment]
Or this is a general login form for all users but the button will lead to a signup form for other types of users and not admin user, so the team working on the other user types will add the redirect to the signup page they create, for now I will just have text-button there but it will not be active

**Comment by sookwalinga** [comment]
@sheyi103 I have put in a pr for this issue. Please merge and move the card to blocked as I am waiting for the api for this. Also please move the other issues assigned to contributors to "in-progress" and all other issues for sprint 1 to "to-do" so that we can easily see what is left for sprint 1, thanks

**Comment by sheyi103** [comment]
The Pull request has been merged. @sookwalinga 

thanks
